'use client';
import {useEffect,useRef,useState} from 'react';
import {BookObject} from './book';
import {Plus,RotateCcw,Save,Send,Sun,Trash2} from 'lucide-react';
type ObjectItem={id:string;type:'shelf'|'chair'|'plant'|'lamp'|'art'|'book';x:number;y:number;rotation:number;scale?:number;color:string;copyId?:string};
type Scene={light:number;objects:ObjectItem[]};
const starter:Scene={light:75,objects:[]};
export function RoomEditor({room,copies,onAction,notice}:{room:any;copies:any[];onAction:(a:string,p:any)=>Promise<unknown>;notice:(m:string)=>void}) {
  const [scene,setScene]=useState<Scene>(room?.draft??starter),[history,setHistory]=useState<Scene[]>([]);
  const [name,setName]=useState(room?.name??'My Room'),[mood,setMood]=useState(room?.mood??'study'),[selected,setSelected]=useState<string|null>(null),[preview,setPreview]=useState(false),[saving,setSaving]=useState(false);
  const dirty=useRef(false),latest=useRef(scene);latest.current=scene;
  useEffect(()=>{setScene(room?.draft??starter);setName(room?.name??'My Room');setMood(room?.mood??'study');dirty.current=false},[room?.id]);
  const change=(next:Scene)=>{setHistory(h=>[...h.slice(-29),scene]);setScene(next);dirty.current=true};
  const save=async()=>{setSaving(true);try{await onAction('room.save',{scene:latest.current,name,mood});dirty.current=false;notice('Draft saved')}finally{setSaving(false)}};
  useEffect(()=>{const timer=setInterval(()=>{if(dirty.current){onAction('room.save',{scene:latest.current,name,mood}).then(()=>{dirty.current=false}).catch(()=>{})}},6000);return()=>clearInterval(timer)},[name,mood,onAction]);
  const add=(type:ObjectItem['type'],copyId?:string)=>change({...scene,objects:[...scene.objects,{id:crypto.randomUUID(),type,x:30+Math.random()*35,y:35+Math.random()*30,rotation:0,scale:1,color:'#805d42',copyId}]});
  const update=(id:string,patch:Partial<ObjectItem>)=>change({...scene,objects:scene.objects.map(o=>o.id===id?{...o,...patch}:o)});
  const active=scene.objects.find(o=>o.id===selected);
  const dragStart=(event:React.PointerEvent<HTMLButtonElement>,objectId:string)=>{if(preview)return;event.currentTarget.setPointerCapture(event.pointerId);setSelected(objectId);setHistory(h=>[...h.slice(-29),scene])};
  const dragMove=(event:React.PointerEvent<HTMLButtonElement>,objectId:string)=>{if(!event.currentTarget.hasPointerCapture(event.pointerId)||preview)return;const rect=event.currentTarget.parentElement?.getBoundingClientRect();if(!rect)return;
    const x=Math.max(0,Math.min(100,(event.clientX-rect.left)/rect.width*100)),y=Math.max(0,Math.min(100,(event.clientY-rect.top)/rect.height*100));
    setScene(current=>({...current,objects:current.objects.map(o=>o.id===objectId?{...o,x,y}:o)}));dirty.current=true;};
  return <div className="room-workspace"><div className="room-header"><div><p className="eyebrow">YOUR SPATIAL LIBRARY</p><h2>Reader’s Room</h2><p>Build a place for your books. Publish only when it feels right.</p></div><div className="row wrap"><button className="button subtle" onClick={()=>setPreview(!preview)}>{preview?'Back to decorate':'Visitor preview'}</button><button className="button subtle" onClick={save} disabled={saving}><Save size={15}/>{saving?'Saving':'Save draft'}</button><button className="button primary" onClick={async()=>{await save();await onAction('room.publish',{audience:'public'});notice('Room published')}}><Send size={15}/> Publish</button></div></div>
    {!preview&&<div className="room-toolbar"><label>Room name<input value={name} onChange={e=>{setName(e.target.value);dirty.current=true}} maxLength={180}/></label><label>Mood<select value={mood} onChange={e=>{setMood(e.target.value);dirty.current=true}}><option value="study">The Study</option><option value="sunroom">Sunroom</option><option value="archive">Archive</option><option value="afterhours">After Hours</option></select></label><label><Sun size={16}/> Light <input type="range" min="0" max="100" value={scene.light} onChange={e=>change({...scene,light:Number(e.target.value)})}/></label><button className="icon-button" title="Undo" onClick={()=>{if(history.length){setScene(history[history.length-1]);setHistory(history.slice(0,-1));dirty.current=true}}} disabled={!history.length}><RotateCcw size={17}/></button></div>}
    <div className="room-layout"><div className={`room-canvas ${mood}`} style={{'--room-light':scene.light/100} as React.CSSProperties} aria-label="Room scene; objects can also be positioned using the controls beneath">
      <div className="room-wall"><div className="room-title">{name}</div></div><div className="room-floor"/>
      {scene.objects.map(obj=><button key={obj.id} className={`room-item ${obj.type} ${selected===obj.id?'selected':''}`} style={{'--object-color':obj.color,left:`${obj.x}%`,top:`${obj.y}%`,transform:`translate(-50%,-50%) rotate(${obj.rotation}deg) scale(${obj.scale??1})`} as React.CSSProperties} onClick={()=>setSelected(obj.id)} onPointerDown={event=>dragStart(event,obj.id)} onPointerMove={event=>dragMove(event,obj.id)} aria-label={`Move or select ${obj.type}`}>
        {obj.type==='book'?<BookObject title={copies.find(c=>c.id===obj.copyId)?.title??'Book'} author={copies.find(c=>c.id===obj.copyId)?.author} photo={copies.find(c=>c.id===obj.copyId)?.front_photo?`/api/media/${copies.find(c=>c.id===obj.copyId)?.front_photo}`:null} interactive={false}/>:obj.type==='shelf'?<span className="furniture shelf-shape"/>:obj.type==='chair'?<span className="furniture chair-shape">◕</span>:obj.type==='plant'?<span className="furniture plant-shape">♣</span>:obj.type==='lamp'?<span className="furniture lamp-shape">✧</span>:<span className="furniture art-shape">✳</span>}
      </button>)}
      {scene.objects.length===0&&<div className="room-empty">A room begins with one object.<br/>Choose a piece below.</div>}
    </div>
    {!preview&&<aside className="room-palette"><h3>Place something</h3><div className="palette-grid">{(['shelf','chair','plant','lamp','art'] as const).map(type=><button key={type} onClick={()=>add(type)}><Plus size={15}/>{type}</button>)}</div><h3>Your physical books</h3>{copies.filter(c=>c.owner_id===room?.user_id||c.holder_id===room?.user_id).length===0?<p className="muted">Add a copy to put it in your Room.</p>:<div className="book-palette">{copies.filter(c=>!['archived'].includes(c.status)).map(c=><button key={c.id} onClick={()=>add('book',c.id)}><span>▰</span><span>{c.title}<small>{c.status}</small></span><Plus size={14}/></button>)}</div>}
      {active&&<div className="selection-tools"><h3>Selected {active.type}</h3><label>Left / right <input type="range" min="0" max="100" value={active.x} onChange={e=>update(active.id,{x:Number(e.target.value)})}/></label><label>Forward / back <input type="range" min="0" max="100" value={active.y} onChange={e=>update(active.id,{y:Number(e.target.value)})}/></label><label>Turn <input type="range" min="-180" max="180" value={active.rotation} onChange={e=>update(active.id,{rotation:Number(e.target.value)})}/></label><label>Size <input type="range" min="0.5" max="2" step="0.1" value={active.scale??1} onChange={e=>update(active.id,{scale:Number(e.target.value)})}/></label><label>Color <input type="color" value={active.color} onChange={e=>update(active.id,{color:e.target.value})}/></label><button className="button danger" onClick={()=>{change({...scene,objects:scene.objects.filter(o=>o.id!==active.id)});setSelected(null)}}><Trash2 size={14}/> Remove</button></div>}
    </aside>}</div><p className="muted tiny">Decorative objects do not change book ownership. Public visitors see only books whose listings and visibility permit it.</p></div>;
}
